// Writes/removes ${worktree}/.env.lease, the per-worktree env file that
// dev tooling sources to discover its allocated port / db name / etc.
//
// Format: KEY=value, one per line, with a header comment marking the
// file as runtime-generated. Values are quoted only when needed.
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
const ENV_LEASE_FILENAME = ".env.lease";
const HEADER = "# Generated by pdh-flow lease — do not edit. Edits are overwritten.";
export function envLeasePath(worktree) {
    return resolve(worktree, ENV_LEASE_FILENAME);
}
export function writeEnvLease(worktree, leases) {
    const path = envLeasePath(worktree);
    if (leases.length === 0) {
        if (existsSync(path)) {
            rmSync(path, { force: true });
        }
        return null;
    }
    const seen = new Set();
    const lines = [HEADER];
    for (const entry of leases) {
        const key = entry.env;
        if (seen.has(key))
            continue;
        seen.add(key);
        lines.push(`${key}=${formatEnvValue(entry.value)}`);
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, lines.join("\n") + "\n");
    return path;
}
export function removeEnvLease(worktree) {
    const path = envLeasePath(worktree);
    if (!existsSync(path))
        return false;
    rmSync(path, { force: true });
    return true;
}
function formatEnvValue(value) {
    if (typeof value === "number")
        return String(value);
    const str = String(value);
    // Quote when the value contains shell-significant characters. Numeric
    // strings, plain identifiers, and dotted/dashed/underscored tokens are
    // safe to leave bare so dotenv-style readers parse them as-is.
    if (/^[A-Za-z0-9_./:@+\-]+$/.test(str))
        return str;
    return `"${str.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"")}"`;
}
